name: gatcor
description: "Aplikasi transportasi online"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.1.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env 